# Generated by Django 3.0.2 on 2022-05-21 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DuoAlgo.Author', verbose_name='Credits to:'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Lesson body in .md format'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(blank=True, default=None, null=True, verbose_name='Lesson duration (optional)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='link_to_code',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Link to sample of code'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tasks',
            field=models.ManyToManyField(to='DuoAlgo.Task', verbose_name='List of related tasks'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default=None, max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
