# Generated by Django 3.0.2 on 2022-05-21 14:59

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0002_auto_20220521_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='body',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='Lesson content in .md format'),
        ),
    ]
