# Generated by Django 3.0.2 on 2022-05-25 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0003_auto_20220521_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='supratopic',
        ),
        migrations.AddField(
            model_name='topic',
            name='supertopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DuoAlgo.Topic'),
        ),
    ]
