# Generated by Django 3.0.2 on 2022-05-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0004_auto_20220525_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['topo_order']},
        ),
        migrations.AddField(
            model_name='topic',
            name='topo_order',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
