# Generated by Django 3.0.2 on 2022-05-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0005_auto_20220525_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topo_order',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
