# Generated by Django 4.0.4 on 2022-06-11 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0007_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DuoAlgo.author', verbose_name='Author'),
        ),
    ]
