# Generated by Django 4.0.4 on 2022-06-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0009_task_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(default='none', max_length=50, verbose_name='Task source'),
            preserve_default=False,
        ),
    ]
