# Generated by Django 4.0.4 on 2022-06-11 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0011_lesson_dependencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='dependencies',
        ),
    ]
