# Generated by Django 4.0.4 on 2022-06-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0012_remove_lesson_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='dependencies',
            field=models.ManyToManyField(to='DuoAlgo.lesson', verbose_name='Things to learn before'),
        ),
    ]
