# Generated by Django 4.0.4 on 2022-06-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0013_lesson_dependencies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edge',
        ),
    ]
