# Generated by Django 4.0.4 on 2022-06-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0014_delete_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.TextField(blank=True, verbose_name='Tags (for now)'),
        ),
    ]
