# Generated by Django 4.0.4 on 2022-06-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0016_alter_task_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='dependencies',
            field=models.ManyToManyField(blank=True, null=True, to='DuoAlgo.lesson', verbose_name='Things to learn before'),
        ),
    ]
