# Generated by Django 4.0.4 on 2022-06-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0017_alter_lesson_dependencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='DuoAlgo.task', verbose_name='List of related tasks'),
        ),
    ]
