# Generated by Django 4.0.4 on 2022-06-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0019_alter_lesson_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Level in stage'),
        ),
    ]
