# Generated by Django 4.0.4 on 2022-06-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0020_lesson_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='DuoAlgo.lesson', verbose_name='Things to learn before'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='DuoAlgo.task', verbose_name='List of related tasks'),
        ),
    ]
