# Generated by Django 4.0.4 on 2022-06-28 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DuoAlgo', '0022_donetasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userext',
            name='completed_lessons',
        ),
        migrations.RemoveField(
            model_name='userext',
            name='current_lesson',
        ),
        migrations.CreateModel(
            name='CompletedLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_progress', models.BooleanField(default=False, verbose_name='Still in progress')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DuoAlgo.lesson', verbose_name='Lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
