# Generated by Django 4.0.4 on 2022-06-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0024_alter_lesson_dependencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='DuoAlgo.lesson', verbose_name='Things to learn before'),
        ),
    ]
