# Generated by Django 4.0.4 on 2022-06-28 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0025_alter_lesson_dependencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='dependencies',
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ins', to='DuoAlgo.lesson')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outs', to='DuoAlgo.lesson')),
            ],
        ),
    ]
