# Generated by Django 4.0.4 on 2022-06-28 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0026_remove_lesson_dependencies_edge'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='lesson',
            order_with_respect_to='stage',
        ),
    ]
