# Generated by Django 4.0.4 on 2022-06-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0027_alter_lesson_order_with_respect_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Just for ordering purposes'),
        ),
    ]
