# Generated by Django 4.0.4 on 2022-06-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0028_edge_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden'),
        ),
    ]
