# Generated by Django 4.0.4 on 2022-06-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DuoAlgo', '0030_topic_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
